name: Continuous Integration

on:
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  end-to-end-tests:
    name: End to End testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install project dependencies
        run: pnpm install --frozen-lockfile

      - name: Install NX globally for caching
        run: pnpm add --global nx

      - name: Install Playwright
        id: install-playwright
        uses: ./.github/actions/playwright

      - name: Debug Playwright cache
        run: |
          echo "Playwright version – ${{ steps.install-playwright.outputs.version }}"
          echo "Playwright cached – ${{ steps.install-playwright.outputs.cache-hit }}"

      - name: Specify the base and head SHAs for the "nx affected" command
        uses: nrwl/nx-set-shas@v4

      - name: Biome lint and formatting
        run: |
          nx biome-check admin &&
          nx biome-check inbox && 
          nx biome-check landing

      - name: Run affected NX targets
        run: nx affected -t build e2e
