name: Continuous Integration

on:
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  end-to-end-tests:
    name: End to End testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js with enabled cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm" # Use pnpm for caching

      - name: Install PNPM globally for faster installs
        run: |
          npm install -g pnpm
          echo "::add-path::$(npm bin -g)"

      - name: Install project dependencies
        run: pnpm install --legacy-peer-deps

      - name: Specify the base and head SHAs for the "nx affected" command
        uses: nrwl/nx-set-shas@v4

      - name: Biome lint and formatting
        run: |
          npx nx biome-check admin &&
          npx nx biome-check inbox && 
          npx nx biome-check landing

      - name: Run affected NX targets
        run: npx nx affected -t build e2e
