name: Continuous Integration

on:
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  end-to-end-tests:
    name: End to End testing with Playwright
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node with enabled cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install project dependencies
        run: npm clean-install --legacy-peer-deps

      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}
          restore-keys: |
            playwright-browsers-

      - name: Install Playwright browsers if not cached
        run: npx playwright install --with-deps

      - name: Specity the base and head SHAs for the "nx affected" command
        uses: nrwl/nx-set-shas@v4

      - name: Biome lint and formating
        run: |
          npx biome check --write apps/admin/src && 
          npx biome check --write apps/inbox/src && 
          npx biome check --write apps/landing/src

      - name: Run affected NX targets
        run: npx nx affected -t build e2e
